// 생성 파일 — 직접 수정하지 마세요. `npm run generate:cn-descriptions`로 재생성합니다.
// 출처: public/templates/CBAM_Communication_template_for_installations_en_20241213.xlsx (Parameters_CNCodes!D·H열, 철강 계열 품목군만)
// 원본 sha256: 5a4e28fdbccfdca45a2c0520184b551a20c0c7bba3db79f87d78c9e58a6c0917

/** 8자리 CN → EU 공식 영문 품명(철강 계열만). 목록에 없다고 CBAM 비대상이라는 뜻은 아니다 — 다른 품목군은 담지 않았다. */
export const CN_DESCRIPTIONS: Readonly<Record<string, string>> = {
    "26011200": "Agglomerated iron ores and concentrates (excl. roasted iron pyrites)",
    "72011011": "Non-alloy pig iron in pigs, blocks or other primary forms, containing by weight <= 0,5% phosphorus, >= 0,4% manganese and <= 1% silicon",
    "72011019": "Non-alloy pig iron in pigs, blocks or other primary forms, containing by weight <= 0,5% phosphorus, >= 0,4% manganese and > 1% silicon",
    "72011030": "Non-alloy pig iron in pigs, blocks or other primary forms, containing by weight <= 0,5% phosphorus, and >= 0,1% but < 0,4% manganese",
    "72011090": "Non-alloy pig iron in pigs, blocks or other primary forms, containing by weight <= 0,5% phosphorus, and <= 0,1% manganese",
    "72012000": "Non-alloy pig iron in pigs, blocks or other primary forms, containing by weight >= 0,5% phosphorus",
    "72015010": "Alloy pig iron in pigs, blocks or other primary forms, containing by weight >= 0,3% but <= 1% titanium and >= 0,5% but <= 1% vanadium",
    "72015090": "Alloy pig iron and spiegeleisen, in pigs, blocks or other primary forms (excl. alloy iron containing, by weight, >= 0,3% but <= 1% titanium and >= 0,5% but <= 1% vanadium)",
    "72021120": "Ferro-manganese, containing by weight > 2% carbon, with a granulometry <= 5 mm and a manganese content by weight > 65%",
    "72021180": "Ferro-manganese, containing by weight > 2% carbon (excl. ferro-manganese with a granulometry of <= 5 mm and containing by weight > 65% manganese)",
    "72021900": "Ferro-manganese, containing by weight <= 2% carbon",
    "72024110": "Ferro-chromium, containing by weight > 4% but <= 6% carbon",
    "72024190": "Ferro-chromium, containing by weight > 6% carbon",
    "72024910": "Ferro-chromium, containing by weight <= 0,05% carbon",
    "72024950": "Ferro-chromium, containing by weight > 0,05% but <= 0,5% carbon",
    "72024990": "Ferro-chromium, containing by weight > 0,5% but <= 4% carbon",
    "72026000": "Ferro-nickel",
    "72031000": "Ferrous products obtained by direct reduction of iron ore, in lumps, pellets or similar forms",
    "72039000": "Spongy ferrous products, obtained from molten pig iron by atomisation, iron of a purity of >= 99,94%, in lumps, pellets or similar forms",
    "72051000": "Granules, of pig iron, spiegeleisen, iron or steel (excl. granules of ferro-alloys, turnings and filings of iron or steel, certain small calibre items, defective balls for ball-bearings)",
    "72052100": "Powders, of alloy steel (excl. powders of ferro-alloys and radioactive iron powders \"isotopes\")",
    "72052900": "Powders, of pig iron, spiegeleisen, iron or non-alloy steel (excl. powders of ferro-alloys and radioactive iron powders \"isotopes\")",
    "72061000": "Ingots, of iron and non-alloy steel (excl. remelted scrap ingots, continuous cast products, iron of heading 7203)",
    "72069000": "Iron and non-alloy steel, in puddled bars or other primary forms (excl. ingots, remelted scrap ingots, continuous cast products, iron of heading 7203)",
    "72071111": "Semi-finished products, of non-alloy free-cutting steel, containing by weight < 0,25% carbon, of square or rectangular cross-section, the width < twice the thickness, rolled or obtained by continuous casting",
    "72071114": "Semi-finished products, of iron or non-alloy steel, containing by weight < 0,25% carbon, of square or rectangular cross-section, the width < twice the thickness of <= 130 mm, rolled or obtained by continuous casting (excl. free-cutting steel)",
    "72071116": "Semi-finished products, of iron or non-alloy steel, containing by weight < 0,25% carbon, of square or rectangular cross-section, the width < twice the thickness of > 130 mm, rolled or obtained by continuous casting (excl. free-cutting steel)",
    "72071190": "Semi-finished products of iron or non-alloy steel, containing by weight < 0,25% carbon, of rectangular cross-section, the width < twice the thickness, forged",
    "72071210": "Semi-finished products of iron or non-alloy steel, containing by weight < 0,25 of carbon, of rectangular \"other than square\" cross-section, the width measuring >= twice the thickness, rolled or obtained by continuous casting",
    "72071290": "Semi-finished products of iron or non-alloy steel, containing by weight < 0,25% carbon, of rectangular \"other than square\" cross-section, the width >= twice the thickness, forged",
    "72071912": "Semi-finished products, of iron or non-alloy steel, containing by weight < 0,25% carbon, of circular or polygonal cross-section, rolled or obtained by continuous casting",
    "72071919": "Semi-finished products of iron or non-alloy steel, containing by weight < 0,25% carbon, of circular or polygonal cross-section, forged",
    "72071980": "Semi-finished products of iron or non-alloy steel, containing by weight < 0,25% carbon (excl. semi-products, of square, rectangular, circular or polygonal cross-section)",
    "72072011": "Semi-finished products, of non-alloy free-cutting steel, containing by weight >= 0,25% carbon, of square or rectangular cross-section, the width < twice the thickness, rolled or obtained by continuous casting",
    "72072015": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,25% but < 0,6% carbon, of square or rectangular cross-section, the width < twice the thickness, rolled or obtained by continuous casting (excl. free-cutting steel)",
    "72072017": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,6% carbon, of square or rectangular cross-section, the width < twice the thickness, rolled or obtained by continuous casting (excl. free-cutting steel)",
    "72072019": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,25% carbon, of square or rectangular cross-section, the width < twice the thickness, forged",
    "72072032": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,25 of carbon, of rectangular \"other than square\" cross-section, the width measuring >= twice the thickness, rolled or obtained by continuous casting",
    "72072039": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,25% carbon, of rectangular \"other than square\" cross-section and the width >= twice the thickness, forged",
    "72072052": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,25% carbon, of circular or polygonal cross-section, rolled or obtained by continuous casting",
    "72072059": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,6% carbon, of circular or polygonal cross-section, forged",
    "72072080": "Semi-finished products of iron or non-alloy steel, containing by weight >= 0,25% carbon (excl. those of square, rectangular, circular or polygonal cross-section)",
    "72081000": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, with patterns in relief directly due to the rolling process",
    "72082500": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 4,75 mm, pickled, without patterns in relief",
    "72082600": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 3 mm but < 4,75 mm, pickled, without patterns in relief",
    "72082700": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of < 3 mm, pickled, without patterns in relief",
    "72083600": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 10 mm, not pickled, without patterns in relief",
    "72083700": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 4,75 mm but < 10 mm, not pickled, without patterns in relief",
    "72083800": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 3 mm but < 4,75 mm, not pickled, without patterns in relief",
    "72083900": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply hot-rolled, not clad, plated or coated, of a thickness of < 3 mm, not pickled, without patterns in relief",
    "72084000": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply hot-rolled, not clad, plated or coated, with patterns in relief directly due to the rolling process",
    "72085120": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of > 15 mm, without patterns in relief",
    "72085191": "Flat-rolled products of iron or non-alloy steel, of a width of >= 2.050 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of > 10 mm but <= 15 mm, without patterns in relief (excl. \"wide flats\")",
    "72085198": "Flat-rolled products of iron or non-alloy steel, of a width of < 2.050 mm but >= 600 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of > 10 mm but <= 15 mm, without patterns in relief",
    "72085210": "Flat-rolled products of iron or non-alloy steel, of a width of <= 1.250 mm, not in coils, simply hot-rolled on four faces or in a closed box pass, not clad, plated or coated, of a thickness of >= 4,75 mm but <= 10 mm, without patterns in relief",
    "72085291": "Flat-rolled products of iron or non-alloy steel, of a width of >= 2.050 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 4,75 mm but <= 10 mm, without patterns in relief",
    "72085299": "Flat-rolled products of iron or non-alloy steel, of a width of < 2.050 mm but >= 600 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 4,75 mm but <= 10 mm, without patterns in relief (excl. rolled on four faces or in a closed bow pass of a width <= 1.250 mm)",
    "72085310": "Flat-rolled products of iron or non-alloy steel, of a width of <= 1.250 mm, not in coils, simply hot-rolled on four faces or in a closed box pass, not clad, plated or coated, of a thickness of >= 4 mm but < 4,75 mm, without patterns in relief",
    "72085390": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of >= 3 mm but < 4,75 mm, without patterns in relief (excl. rolled on four faces or in a closed bow pass of a width <= 1.250 mm and of a thickness of >= 4 mm)",
    "72085400": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply hot-rolled, not clad, plated or coated, of a thickness of < 3 mm, without patterns in relief",
    "72089020": "Flat-rolled products of iron or steel, of a width >= 600 mm, hot-rolled and further worked, but not clad, plated or coated, perforated",
    "72089080": "Flat-rolled products of iron or steel, of a width >= 600 mm, hot-rolled and further worked, but not clad, plated or coated, non-perforated",
    "72091500": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of >= 3 mm",
    "72091610": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", of a thickness of > 1 mm but < 3 mm \"electrical\"",
    "72091690": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of > 1 mm but < 3 mm (excl. electrical)",
    "72091710": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", of a thickness of >= 0,5 mm but <= 1 mm \"electrical\"",
    "72091790": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of >= 0,5 mm but <= 1 mm (excl. electrical)",
    "72091810": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", of a thickness of < 0,5 mm \"electrical\"",
    "72091891": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of >= 0,35 mm but < 0,5 mm (excl. electrical)",
    "72091899": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of < 0,35 mm (excl. electrical)",
    "72092500": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of >= 3 mm",
    "72092610": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", of a thickness of > 1 mm but < 3 mm \"electrical\"",
    "72092690": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of > 1 mm but < 3 mm (excl. electrical)",
    "72092710": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", of a thickness of >= 0,5 mm but <= 1 mm \"electrical\"",
    "72092790": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of >= 0,5 mm but <= 1 mm (excl. electrical)",
    "72092810": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", of a thickness of < 0,5 mm \"electrical\"",
    "72092890": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, not in coils, simply cold-rolled \"cold-reduced\", not clad, plated or coated, of a thickness of < 0,5 mm (excl. electrical)",
    "72099020": "Flat-rolled products of iron or steel, of a width of >= 600 mm, cold-rolled \"cold-reduced\" and further worked, but not clad, plated or coated, perforated",
    "72099080": "Flat-rolled products of iron or steel, of a width of >= 600 mm, cold-rolled \"cold-reduced\" and further worked, but not clad, plated or coated, non-perforated",
    "72101100": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", tinned, of a thickness of >= 0,5 mm",
    "72101220": "Tinplate of iron or non-alloy steel, of a width of >= 600 mm and of a thickness of < 0,5 mm, tinned [coated with a layer of metal containing, by weight, >= 97% of tin], not further worked than surface-treated",
    "72101280": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with tin, of a thickness of < 0,5 mm (excl. tinplate)",
    "72102000": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with lead, incl. terne-plate",
    "72103000": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", electrolytically plated or coated with zinc",
    "72104100": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", corrugated, plated or coated with zinc (excl. electrolytically plated or coated with zinc)",
    "72104900": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", not corrugated, plated or coated with zinc (excl. electrolytically plated or coated with zinc)",
    "72105000": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with chromium oxides or with chromium and chromium oxides",
    "72106100": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with aluminium-zinc alloys",
    "72106900": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with aluminium (excl. products plated or coated with aluminium-zinc alloys)",
    "72107010": "Tinplate of a width of >= 600 mm and of a thickness of < 0,5 mm, tinned [coated with a layer of metal containing, by weight, >= 97% of tin], not further worked than varnished, and flat products plated or coated with chromium oxides or with chromium and chromium oxides, of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", varnished",
    "72107080": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", painted, varnished or plastic coated (excl. tinplate and products electrolytically plated or coated with chrome, varnished)",
    "72109030": "Flat-rolled products of iron or non-alloy steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\", clad",
    "72109040": "Flat-rolled products of iron or non-alloy steel, tinned and printed, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\"",
    "72109080": "Flat-rolled products of iron or non-alloy steel, hot-rolled or cold-rolled \"cold-reduced\", of a width of >= 600 mm, plated or coated (excl. plated or coated with thin, lead \"incl. terne-plate\", zinc, aluminium, chromium, chromium oxides, plastics, platinum, painted or varnished, clad and tinned and printed)",
    "72111300": "Flat-rolled products of iron or non-alloy steel, simply hot-rolled on four faces or in a closed box pass, not clad, plated or coated, of a width of > 150 mm but < 600 mm and a thickness of >= 4 mm, not in coils, without patterns in relief, commonly known as \"wide flats\"",
    "72111400": "Flat-rolled products of iron or non-alloy steel, of a width < 600 mm, not further worked than hot-rolled, not clad, plated or coated, of a thickness of >= 4,75 mm (excl. \"wide flats\")",
    "72111900": "Flat-rolled products of iron or non-alloy steel, of a width < 600 mm, simply hot-rolled, not clad, plated or coated, of a thickness < 4,75 mm (excl. \"wide flats\")",
    "72112320": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, simply cold-rolled \"cold-reduced\", not clad, plated or coated, containing by weight < 0,25% of carbon \"electrical\"",
    "72112330": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm and of a thickness of >= 0,35 mm, simply cold-rolled \"cold-reduced\", not clad, plated or coated, containing by weight < 0,25% of carbon (excl. electrical plate)",
    "72112380": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm and of a thickness of < 0,35 mm, simply cold-rolled \"cold-reduced\", not clad, plated or coated, containing by weight < 0,25% of carbon (excl. electrical plate)",
    "72112900": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, simply cold-rolled \"cold-reduced\", not clad, plated or coated, containing by weight >= 0,25% of carbon",
    "72119020": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked, but not clad, plated or coated, perforated",
    "72119080": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked, but not clad, plated or coatednon-perforated",
    "72121010": "Tinplate of iron or non-alloy steel, of a width of < 600 mm and of a thickness of < 0,5 mm, tinned [coated with a layer of metal containing, by weight, >= 97% of tin], not further worked than surface-treated",
    "72121090": "Flat-rolled products of iron or non-alloy steel, hot-rolled or cold-rolled \"cold-reduced\", of a width of < 600 mm, tinned (excl. tinplate, not further worked than surface-treated)",
    "72122000": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", electrolytically plated or coated with zinc",
    "72123000": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", tinned (excl. electrolytically plated or coated with zinc)",
    "72124020": "Tinplate of a width of < 600 mm and of a thickness of < 0,5 mm, tinned [coated with a layer of metal containing, by weight, >= 97% of tin], not further worked than varnished, and flat products plated or coated with chromium oxides or with chromium and chromium oxides, of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", varnished",
    "72124080": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", painted, varnished or plastic coated (excl. tinplate, not further worked than varnished, and products plated or coated with chromium oxides or with chromium and chromium oxides, varnished)",
    "72125020": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with chromium oxides or with chromium and chromium oxides (excl. varnished)",
    "72125030": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with chromium or nickel",
    "72125040": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with copper",
    "72125061": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with aluminium-zinc alloys",
    "72125069": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", plated or coated with aluminium (excl. products plated or coated with aluminium-zinc alloys)",
    "72125090": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", clad (excl. products plated or coated with tin or zinc, copper, with chromium oxides or with chromium and chromium oxides, chromium, nickel or aluminium, painted or varnished, and plastic-coated)",
    "72126000": "Flat-rolled products of iron or non-alloy steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", clad",
    "72131000": "Bars and rods, hot-rolled, in irregularly wound coils of iron or non-alloy steel, with indentations, ribs, grooves or other deformations produced during the rolling process",
    "72132000": "Bars and rods, hot-rolled, in irregularly wound coils, of non-alloy free-cutting steel (excl. bars and rods containing indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72139110": "Bars and rods, hot-rolled, of the type used for concrete reinforcement, smooth, of iron or non-alloy steel, in irregularly wound coils, of circular cross-section measuring < 14 mm in diameter",
    "72139120": "Bars and rods, hot-rolled, of the type used for tyre cord, smooth, of iron or non-alloy steel, in irregularly wound coils",
    "72139141": "Bars and rods, hot-rolled, of iron or non-alloy steel, in irregularly wound coils, containing by weight <= 0,06% of carbon, of circular cross-section measuring < 14 mm in diameter (excl. free-cutting steel, bars and rods, hot-rolled, for concrete reinforcement and tyre cord, and bars and rods, hot-rolled, containing indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72139149": "Bars and rods, hot-rolled, of iron or non-alloy steel, in irregularly wound coils, containing by weight > 0,06% and < 0,25% of carbon, of circular cross-section, measuring < 14 mm in diameter (excl. of free-cutting steel, bars and rods, hot-rolled, for concrete reinforcement and tyre cord and bars and rods, hot-rolled, containing indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72139170": "Bars and rods, hot-rolled, in irregularly wound coils, of iron or non-alloy steel, containing by weight >= 0,25% but <= 0,75% carbon, of circular cross-section measuring < 14 mm in diameter (excl. of free-cutting steel, and bars and rods, smooth, for concrete reinforcement and tyre cord, and bars and rods with indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72139190": "Bars and rods, hot-rolled, of iron or non-alloy steel, in irregularly wound coils, containing by weight > 0,75% of carbon, of circular cross-section measuring < 14 mm in diameter (excl. of free-cutting steel, bars and rods, smooth, for tyre cord and bars and rods with indentations, ribs, grooves and other deformations produced during the rolling process)",
    "72139910": "Bars and rods, of iron or non-alloy steel, hot-rolled, in irregularly wound coils, containing by weight < 0,25% carbon (excl. products of circular cross-section measuring < 14 mm in diameter, bars and rods of free-cutting steel, and bars and rods with indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72139990": "Bars and rods, hot-rolled, in irregularly wound coils, of iron or non-alloy steel, containing by weight >= 0,25% carbon (excl. products of circular cross-section measuring < 14 mm diameter, bars and rods of free-cutting steel, and bars and rods with indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72141000": "Bars and rods, of iron or non-alloy steel, not further worked than forged (excl. in irregularly wound coils)",
    "72142000": "Bars and rods, of iron or non-alloy steel, with indentations, ribs, groves or other deformations produced during the rolling process",
    "72143000": "Bars and rods, of non-alloy free-cutting steel, not further worked than hot-rolled, hot-drawn or hot-extruded (excl. containing indentations, ribs, grooves or other deformations produced during the rolling process or twisted after rolling)",
    "72149110": "Bars and rods of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or hot-extruded, containing by weight < 0,25% of carbon, of rectangular \"other than square\" cross-section (excl. those with indentations, ribs, grooves or other deformations produced during the rolling process, bars and rods twisted after rolling, and free-cutting steel)",
    "72149190": "Other bars and rods of iron or non-alloy steel, only hot-rolled, only hot-drawn or only hot-extruded, containing by weight >= 0,25% of carbon, of rectangular \"other than square\" cross-section (excl. those with indentations, ribs, grooves or other deformations produced during the rolling process, bars and rods twisted after rolling, and free-cutting steel)",
    "72149910": "Bars and rods of the type used for concrete reinforcement, smooth, of iron or non-alloy steel, only hot-rolled, only hot-drawn or only hot-extruded, containing < 0,25% of carbon, of square cross-section or of a cross-section other than rectangular",
    "72149931": "Bars and rods of iron or non-alloy steel, only hot-rolled, hot-drawn or hot-extruded, containing < 0,25% of carbon, of circular cross-section, of a maximum diameter of >= 80 mm (other than of free-cutting steel, smooth bars and rods, for reinfoced concrete, or bars and rods containing indentations, ribs, grooves or other deformations produced during the rolling process, or wound after rolling)",
    "72149939": "Bars and rods of iron or non-alloy steel, only hot-rolled, hot-drawn or hot-extruded, containing < 0,25% of carbon, of circular cross-section of a maximum diameter of < 80 mm (other than of free-cutting steel, smooth bars and rods, for reinforced concrete, or bars and rods containing indentations, ribs, grooves or other deformations produced during the rolling process, or wound after rolling)",
    "72149950": "Bars and rods of iron or non-alloy steel, only hot-rolled, hot-drawn or hot-extruded, containing by weight < 0,25% of carbon, of square cross-section or of a cross-section other than square or circular (other than of free-cutting steel, smooth bars and rods, for reinforced concrete, or bars and rods containing indentations, ribs, grooves or other deformations produced during the rolling process, or wound after rolling)",
    "72149971": "Bars and rods of iron or non-alloy steel, only hot-rolled, only hot-drawn or only hot-extruded, containing by weight >= 0,25% carbon, of circular cross-section measuring >= 80 mm in diameter (excl. bars and rods with indentations, ribs, grooves or other deformations produced during the rolling process, twisted after rolling, and of free-cutting steel)",
    "72149979": "Bars and rods of iron or non-alloy steel, only hot-rolled, only hot-drawn or only hot-extruded, containing by weight >= 0,25% carbon, of circular cross-section measuring < 80 mm in diameter (excl. bars and rods with indentations, ribs, grooves or other deformations produced during the rolling process, twisted after rolling, and of free-cutting steel)",
    "72149995": "Bars and rods of iron or non-alloy steel, only hot-rolled, only hot-drawn or only hot-extruded, containing by weight >= 0,25% carbon, of square or of other than rectangular or circular cross-section (excl. indentations, ribs, grooves or other deformations produced during the rolling process, twisted fter rolling, and of free-cutting steel)",
    "72151000": "Bars and rods, of non-alloy free-cutting steel, not further worked than cold-formed or cold-finished",
    "72155011": "Other bars and rods of iron or non-alloy steel, not further worked than cold-formed or cold-finished, containing by weight < 0,25% of carbon of rectangular \"other than square\" cross-section (excl. those of free-cutting steel)",
    "72155019": "Other bars and rods of iron or non-alloy steel, not further worked than cold-formed or cold-finished, containing by weight < 0,25% of carbon, of square or other than rectangular cross-section (excl. those of free-cutting steel)",
    "72155080": "Other bars and rods of iron or non-alloy steel, not further worked than cold-formed or cold-finished, containing by weight >= 0,25% of carbon (excl. those of free-cutting steel)",
    "72159000": "Bars or rods, of iron or non-alloy steel, cold-formed or cold-finished and further worked or hot-formed and further worked, n.e.s.",
    "72161000": "U, I or H sections of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or extruded, of a height of < 80 mm",
    "72162100": "L sections of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or extruded, of a height of < 80 mm",
    "72162200": "T sections of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or extruded, of a height of < 80 mm",
    "72163110": "U sections of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height >= 80 mm but <= 220 mm",
    "72163190": "U sections of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height > 220 mm",
    "72163211": "I sections with parallel flange faces, of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height >= 80 mm but <= 220 mm",
    "72163219": "I sections of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height >= 80 mm but <= 220 mm (excl. 7216.32.11)",
    "72163291": "I sections with parallel flange faces, of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height > 220 mm",
    "72163299": "I sections of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height > 220 mm (excl. 7216.32.91)",
    "72163310": "H sections of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height >= 80 mm but <= 180 mm",
    "72163390": "H sections of iron or non-alloy steel, simply hot-rolled, hot-drawn or extruded, of a height > 180 mm",
    "72164010": "L sections of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or extruded, of a height of >= 80 mm",
    "72164090": "T sections of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or extruded, of a height of >= 80 mm",
    "72165010": "Sections of iron or non-alloy steel, not further worked than hot-rolled, hot-drawn or hot-extruded, with a cross-section which is capable of being enclosed in a square the side of which is <= 80 mm (excl. U, I, H, L or T sections)",
    "72165091": "Bulb sections \"bulb flat\", only hot-rolled, hot-drawn or hot-extruded",
    "72165099": "Profile of iron or non-alloy steel, only hot-rolled, hot-drawn or hot-extruded (other than with a cross-section which is capable of being enclosed in a square the side of which is <= 80 mm, and U-, I-, H-, L- or T-sections and ribbed sections [ribbed steel])",
    "72166110": "c, l, u, z, omega or open-ended sections of iron or non-alloy steel, simply cold-formed or cold-finished, obtained from flat-rolled products",
    "72166190": "Angles, shapes and sections (other than c, l, u, z, omega or open-ended sections) of iron or non-alloy steel, simply cold-formed or cold-finished, obtained from flat-rolled products",
    "72166900": "Angles, shapes and sections, of iron or non-alloy steel, not further worked than cold-formed or cold-finished (excl. profiled sheet)",
    "72169110": "Sheets sheets of iron or non-alloy steel, cold-formed or cold finished, profiled \"ribbed\"",
    "72169180": "Angles, shapes and sections, of iron or non-alloy steel, cold-formed or cold-finished from flat-rolled products and further worked (excl. profiled sheet)",
    "72169900": "Angles, shapes and sections, of iron or non-alloy steel, cold-formed or cold-finished and further worked, or hot-forged, or hot-formed by other means and further worked, n.e.s. (excl. from flat-rolled products)",
    "72171010": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, not plated or coated, whether or not polished, with a maximum cross-sectional dimension of < 0,8 mm",
    "72171031": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, with indentations, ribs, grooves or other deformations produced during the rolling process, not plated or coated, with a maximum cross-sectional dimension of >= 0,8 mm",
    "72171039": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, not plated or coated, with a maximum cross-sectional dimension of >= 0,8 mm (without indentations, ribs, grooves or other deformations produced during the rolling process)",
    "72171050": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,25% but < 0,6% carbon, not plated or coated, whether or not polished (excl. hot-rolled bars and rods)",
    "72171090": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,6% carbon, not plated or coated, whether or not polished (excl. hot-rolled bars and rods)",
    "72172010": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, plated or coated with zinc, with a maximum cross-sectional dimension of < 0,8 mm",
    "72172030": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, plated or coated with zinc, with a maximum cross-sectional dimension of < 0,8 mm (excl. bars and rods)",
    "72172050": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,25% but < 0,6% carbon, plated or coated with zinc (excl. bars and rods)",
    "72172090": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,6% carbon, plated or coated with zinc (excl. bars and rods)",
    "72173041": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, copper-coated (excl. bars and rods)",
    "72173049": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, plated or coated with base metals (excl. products plated or coated with zinc or copper and bars and rods)",
    "72173050": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,25% but < 0,6% carbon, plated or coated with base metals (excl. products plated or coated with zinc, and bars and rods)",
    "72173090": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,6% carbon, plated or coated with base metals (excl. products plated or coated with zinc, and bars and rods)",
    "72179020": "Wire of iron or non-alloy steel, in coils, containing by weight < 0,25% carbon, plated or coated (excl. products plated or coated with base metals and bars and rods)",
    "72179050": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,25% but < 0,6% carbon, plated or coated (excl. products plated or coated with with base metals, and bars and rods)",
    "72179090": "Wire of iron or non-alloy steel, in coils, containing by weight >= 0,6% carbon, plated or coated (excl. products plated or coated with base metals, and bars and rods)",
    "72181000": "Steel, stainless, in ingots and other primary forms (excl. waste and scrap in ingot form, and products obtained by continuous casting)",
    "72189110": "Semi-finished products of stainless steel, of rectangular \"other than square\" cross-section, containing by weight >= 2,5% nickel",
    "72189180": "Semi-finished products of stainless steel, of rectangular \"other than square\" cross-section, containing by weight < 2,5 nickel",
    "72189911": "Semi-finished products of stainless steel, of square cross-section, rolled or obtained by continuous casting",
    "72189919": "Semi-finished products of stainless steel, of square cross-section, forged",
    "72189920": "Semi-finished products of stainless steel, of circular cross-section or of cross-section other than square or rectangular, rolled or obtained by continuous casting",
    "72189980": "Semi-finished products of stainless steel, forged (excl. products of square or rectangular cross-section)",
    "72191100": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of > 10 mm",
    "72191210": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of >= 4,75 mm but <= 10 mm, containing by weight >= 2,5 nickel",
    "72191290": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of >= 4,75 mm but <= 10 mm, containing by weight < 2,5 nickel",
    "72191310": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of >= 3 mm but <= 4,75 mm, containing by weight >= 2,5 nickel",
    "72191390": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of >= 3 mm but <= 4,75 mm, containing by weight < 2,5 nickel",
    "72191410": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of < 3 mm, containing by weight >= 2,5 nickel",
    "72191490": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils, of a thickness of < 3 mm, containing by weight < 2,5 nickel",
    "72192110": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of > 10 mm, containing by weight >= 2,5 nickel",
    "72192190": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of > 10 mm, containing by weight < 2,5 nickel",
    "72192210": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of >= 4,75 mm but <= 10 mm, containing by weight >= 2,5% nickel",
    "72192290": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of >= 4,75 mm but <= 10 mm, containing by weight < 2,5% nickel",
    "72192300": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of >= 3 mm and < 4,75 mm",
    "72192400": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of < 3 mm",
    "72193100": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 4,75 mm",
    "72193210": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 3 mm but <= 4,75 mm, containing by weight >= 2,5% nickel",
    "72193290": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 3 mm but <= 4,75 mm, containing by weight < 2,5% nickel",
    "72193310": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of > 1 mm but < 3 mm, containing by weight >= 2,5% nickel",
    "72193390": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of > 1 mm but < 3 mm, containing by weight < 2,5% nickel",
    "72193410": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 0,5 mm but <= 1 mm, containing by weight >= 2,5% nickel",
    "72193490": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 0,5 mm but <= 1 mm, containing by weight < 2,5% nickel",
    "72193510": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of < 0,5 mm, containing by weight >= 2,5% nickel",
    "72193590": "Flat-rolled products of stainless steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of < 0,5 mm, containing by weight < 2,5% nickel",
    "72199020": "Flat-rolled products of stainless steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked, perforated",
    "72199080": "Flat-rolled products of stainless steel, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked, non-perforated",
    "72201100": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than hot-rolled, of a thickness of >= 4,75 mm",
    "72201200": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than hot-rolled, of a thickness of < 4,75 mm",
    "72202021": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 3 mm and containing by weight >= 2,5% nickel",
    "72202029": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of >= 3 mm and containing by weight < 2,5% nickel",
    "72202041": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of > 0,35 mm but < 3 mm, and containing by weight >= 2,5% nickel",
    "72202049": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of > 0,35 mm but < 3 mm, and containing by weight < 2,5% nickel",
    "72202081": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of <= 0,35 mm and containing by weight >= 2,5% nickel",
    "72202089": "Flat-rolled products of stainless steel, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\", of a thickness of <= 0,35 mm and containing by weight < 2,5% nickel",
    "72209020": "Flat-rolled products of stainless steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked, perforated",
    "72209080": "Flat-rolled products of stainless steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked, non-perforated",
    "72210010": "Bars and rods of stainless steel, hot-rolled, in irregularly wound coils, containing by weight >= 2,5% nickel",
    "72210090": "Bars and rods of stainless steel, hot-rolled, in irregularly wound coils, containing by weight < 2,5% nickel",
    "72221111": "Bars and rods of stainless steel, not further worked than hot-rolled, hot-drawn or extruded, of circular cross-section of a diameter of >= 800 mm, containing by weight >= 2,5% nickel",
    "72221119": "Bars and rods of stainless steel, not further worked than hot-rolled, hot-drawn or extruded, of circular cross-section of a diameter of >= 800 mm, containing by weight < 2,5% nickel",
    "72221181": "Bars and rods of stainless steel, not further worked than hot-rolled, hot-drawn or extruded, of circular cross-section measuring < 80 mm and containing by weight >= 2,5% nickel",
    "72221189": "Bars and rods of stainless steel, not further worked than hot-rolled, hot-drawn or extruded, of circular cross-section measuring < 80 mm and containing by weight < 2,5% nickel",
    "72221910": "Bars and rods of stainless steel, not further worked than hot-rolled, hot-drawn or extruded, containing by weight >= 2,5% nickel (excl. such products of circular cross-section)",
    "72221990": "Bars and rods of stainless steel, not further worked than hot-rolled, hot-drawn or extruded, containing by weight < 2,5% nickel (excl. such products of circular cross-section)",
    "72222011": "Bars and rods of stainless steel, of circular cross-section of a diameter >= 80 mm, simply cold-formed or cold-finished, containing by weight >= 2,5% nickel",
    "72222019": "Bars and rods of stainless steel, of circular cross-section of a diameter >= 80 mm, simply cold-formed or cold-finished, containing by weight < 2,5% nickel",
    "72222021": "Bars and rods of stainless steel, not further worked than cold-formed or cold-finished, of circular cross-section measuring >= 25 mm but < 80 mm and containing by weight >= 2,5% nickel",
    "72222029": "Bars and rods of stainless steel, not further worked than cold-formed or cold-finished, of circular cross-section measuring >= 25 mm but < 80 mm and containing by weight < 2,5% nickel",
    "72222031": "Bars and rods of stainless steel, not further worked than cold-formed or cold-finished, of circular cross-section measuring < 25 mm and containing by weight >= 2,5% nickel",
    "72222039": "Bars and rods of stainless steel, not further worked than cold-formed or cold-finished, of circular cross-section measuring < 25 mm and containing by weight < 2,5% nickel",
    "72222081": "Bars and rods of stainless steel, not further worked than cold-formed or cold-finished, containing by weight >= 2,5% nickel (excl. such products of circular cross-section)",
    "72222089": "Bars and rods of stainless steel, not further worked than cold-formed or cold-finished, containing by weight < 2,5% nickel (excl. such products of circular cross-section)",
    "72223051": "Other bars and rods of stainless steel, containing by weight >= 2,5% of nickel, forged",
    "72223091": "Other bars and rods of stainless steel, containing by weight < 2,5% of nickel, forged",
    "72223097": "Bars and rods of stainless steel, cold-formed or cold-finished and further worked, or hot-formed and further worked, n.e.s. (excl. forged products)",
    "72224010": "Angles, shapes and sections of stainless steel, only hot-rolled, only hot-drawn or only extruded",
    "72224050": "Angles, shapes and sections of stainless steel, not further worked than cold-formed or cold-finished",
    "72224090": "Angles, shapes and sections of stainless steel, cold-formed or cold-finished and further worked, or not further worked than forged, or forged, or hot-formed by other means and further worked, n.e.s.",
    "72230011": "Wire of stainless steel, in coils, containing by weight 28% to 31% nickel and 20% to 22% chromium (excl. bars and rods)",
    "72230019": "Wire of stainless steel, in coils, containing by weight >= 2,5% nickel (excl. such products containing 28% to 31% nickel and 20% to 22% chromium, and bars and rods)",
    "72230091": "Wire of stainless steel, in coils, containing by weight < 2,5% nickel, 13% to 25% chromium and 3,5% to 6% aluminium (excl. bars and rods)",
    "72230099": "Wire of stainless steel, in coils, containing by weight < 2,5% nickel (excl. such products containing 13% to 25% chromium and 3,5% to 6% aluminium, and bars and rods)",
    "72241010": "Ingots and other primary forms, of tool steel",
    "72241090": "Steel, alloy, other than stainless, in ingots or other primary forms (excl. of tool steel, waste and scrap in ingot form and products obtained by continuous casting)",
    "72249002": "Semi-finished products of tool steel",
    "72249003": "Semi-finished products of high-speed steel, of square or rectangular cross-section, hot-rolled or obtained by continuous casting the width measuring < twice the thickness",
    "72249005": "Semi-finished products of steel containing by weight <= 0,7% of carbon, 0,5% to 1,2% of manganese, 0,6% to 2,3% of silicon, or of steel containing by weight >= 0,0008% of boron with any other element < the minimum content referred to in Note 1 f to chapter 72, of square or rectangular cross-section, hot rolled or obtained by continuous casting, the width measuring < twice the thickness",
    "72249007": "Semi-finished products of alloy steel other than stainless steel, of square or rectangular cross-section, hot-rolled or obtained by continuous casting, the width measuring < twice the thickness (excl. of tool steel, high-speed steel and articles of subheading 7224.90.05)",
    "72249014": "Semi-finished products of alloy steel other than stainless steel, of square or rectangular cross-section, hot-rolled or obtained by continuous casting, the width measuring >= twice the thickness (excl. of tool steel)",
    "72249018": "Semi-finished products of alloy steel other than stainless steel, of square or rectangular cross-section, forged (excl. of tool steel)",
    "72249031": "Semi-finished products of steel containing by weight 0,9% to 1,15% carbon, 0,5% to 2% of chromium and, if present, <= 0,5% of molybdenum, cut into shapes other than square or rectangular, hot-rolled or obtained by continuous casting",
    "72249038": "Semi-finished products of alloy steel, other than stainless steel, cut into shapes other than square or rectangular, hot-rolled or obtained by continuous casting (excl. of tool steel and products containing by weight 0,9% to 1,15% of carbon, 0,5% to 2% of chromium and, if present, <= 0,5% of molybdenum)",
    "72249090": "Semi-finished products of alloy steel, other than stainless steel, forged (excl. of tool steel and products of square or rectangular, circular or polygamol cross-section)",
    "72251100": "Flat-rolled products of silicon-electrical steel, of a width of >= 600 mm, grain-oriented",
    "72251910": "Flat-rolled products of silicon-electrical steel, of a width of >= 600 mm, hot-rolled",
    "72251990": "Flat-rolled products of silicon-electrical steel, of a width of >= 600 mm, cold-rolled \"cold-reduced\", non-grain-oriented",
    "72253010": "Flat-rolled products of tool steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils",
    "72253030": "Flat-rolled products of high-speed steel, of a width of >= 600 mm, not further worked than hot-rolled, in coils",
    "72253090": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, not further worked than hot-rolled, in coils (excl. products of tool steel, high-speed steel or silicon-electrical steel)",
    "72254012": "Flat-rolled products of tool steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils",
    "72254015": "Flat-rolled products of high-speed steel, of a width of >= 600 mm, not further worked than hot-rolled, not in coils",
    "72254040": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of > 10 mm (excl. products of tool steel, high-speed steel or silicon-electrical steel)",
    "72254060": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of >= 4,75 mm but <= 10 mm (excl. products of tool steel, high-speed steel or silicon-electrical steel)",
    "72254090": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, not further worked than hot-rolled, not in coils, of a thickness of < 4,75 mm (excl. products of tool steel, high-speed steel or silicon-electrical steel)",
    "72255020": "Flat-rolled products of high-speed steel, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\"",
    "72255080": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, not further worked than cold-rolled \"cold-reduced\" (excl. products of high-speed steel or silicon-electrical steel)",
    "72259100": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and electrolytically plated or coated with zinc (excl. products of silicon-electrical steel)",
    "72259200": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and plated or coated with zinc (excl. electrolytically plated or coated and products of silicon-electrical steel)",
    "72259900": "Flat-rolled products of alloy steel other than stainless, of a width of >= 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked (excl. plated or coated with zinc and products of silicon-electrical steel)",
    "72261100": "Flat-rolled products of silicon-electrical steel, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\", grain-oriented",
    "72261910": "Flat-rolled products of silicon-electrical steel, of a width of < 600 mm, not further worked than hot-rolled",
    "72261980": "Flat-rolled products of silicon-electrical steel, of a width of < 600 mm, cold-rolled \"cold-reduced\", whether or not further worked, or hot-rolled and further worked, non-grain-oriented",
    "72262000": "Flat-rolled products of high-speed steel, of a width of <= 600 mm, hot-rolled or cold-rolled \"cold-reduced\"",
    "72269120": "Flat-rolled products of tool steel, of a width of < 600 mm, simply hot-rolled",
    "72269191": "Flat-rolled products of alloy steel other than stainless steel, simply hot-rolled, of a thickness of >= 4,75 mm, of a width of < 600 mm (excl. of tool steel, silicon-electrical steel or high speed steel)",
    "72269199": "Flat-rolled products of alloy steel other than stainless steel, simply hot-rolled, of a thickness of < 4,75 mm, of a width of < 600 mm (excl. of tool steel, silicon-electrical steel or high speed steel)",
    "72269200": "Flat-rolled products of alloy steel other than stainless, of a width of < 600 mm, not further worked than cold-rolled \"cold-reduced\" (excl. products of high-speed steel or silicon-electrical steel)",
    "72269910": "Flat-rolled products of alloy steel other than stainless, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and electrolytically plated or coated with zinc (excl. products of high-speed steel or silicon-electrical steel)",
    "72269930": "Flat-rolled products of alloy steel other than stainless, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and plated or coated with zinc (excl. electrolytically plated or coated, and products of high-speed steel or silicon-electrical steel)",
    "72269970": "Flat-rolled products of alloy steel other than stainless, of a width of < 600 mm, hot-rolled or cold-rolled \"cold-reduced\" and further worked (excl. plated or coated with zinc, and products of high-speed steel or silicon-electrical steel)",
    "72271000": "Bars and rods of high-speed steel, hot-rolled, in irregularly wound coils",
    "72272000": "Bars and rods of silico-manganese steel, hot-rolled, in irregularly wound coils",
    "72279010": "Bars and rods, hot-rolled, of steel containing by weight >= 0,0008% of boron with any other element < the minimum content referred to in Note 1 f to this chapter, in irregularly wound coils",
    "72279050": "Bars and rods, hot-rolled, of steel containing by weight 0,9% to 1,15% carbon, 0,5% to 2% of chromium and, if present, <= 0,5 of molybdenum, in irregularly wound coils",
    "72279095": "Bars and rods, hot-rolled, in irregularly wound coils of alloy steel other than stainless (excl. of high-speed steel or silico-manganese steel and bars and rods of subheadings 7227.90.10 and 7227.90.50)",
    "72281020": "Bars and rods of high-speed steel, not further worked than hot-rolled, hot-drawn or extruded, and hot-rolled, hot-drawn or extruded, not further worked than clad (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72281050": "Bars and rods of high-speed steel, forged (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72281090": "Bars and rods of high-speed steel, not further worked than cold-formed or cold-finished, whether or not further worked, or hot-formed and further worked (excl. forged products, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72282010": "Bars and rods of silico-manganese steel, of rectangular \"other than square\" cross-section, hot-rolled on four faces (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72282091": "Bars and rods of silico-manganese steel, of square or other than rectangular cross-section, not further worked than hot-rolled, hot-drawn or extruded, and hot-rolled, hot-drawn or extruded, not further worked than clad (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72282099": "Bars and rods of silico-manganese stee, of square or other than rectangular cross-section, only cold-formed or cold-finished, incl. further worked, or hot-rolled and further worked (excl. hot-rolled, hot drawn or extruded, not further worked than clad, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283020": "Bars and rods of tool steel, only hot-rolled, only hot-drawn or only extruded (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283041": "Bars and rods of steel containing by weight 0,9 to 1,15% of carbon and 0,5 to 2% of chromium, and, if present, <= 0,5% of molybdenum, only hot-rolled, hot-drawn or hot-extruded, of a circular cross-section of a diameter of >= 80 mm (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283049": "Bars and rods of steel containing by weight 0,9 to 1,15% of carbon and 0,5 to 2% of chromium, and, if present, <= 0,5% of molybdenum, only hot-rolled, only hot-drawn or hot-extruded (other than of circular cross-section, of a diameter of >= 80 mm and excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283061": "Bars and rods of alloy steel other than stainless steel, only hot-rolled, hot-drawn or hot-extruded, of circular cross-section, of a diameter of >= 80 mm (other than of high-speed steel, silico-manganese steel, tool steel, articles of subheading 7228.30.41 and excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283069": "Bars and rods or alloy steel other than stainless steel, only hot-rolled, hot-drawn or hot-extruded, of circular cross-section, of a diameter of < 80 mm (other than of high-speed steel, silico-manganese steel, tool steel and articles of subheading 7228.30.49 and excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283070": "Bars and rods of alloy steel other than stainless steel, of rectangular \"other than square\" cross-section, hot-rolled on four faces (other than of high-speed steel, silico-manganese steel, tool steel, articles of subheading 7228.30.41 and 7228.30.49 and excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72283089": "Bars and rods of alloy steel other than stainless steel, only hot-rolled, hot-drawn or hot-extruded, of other than rectangular [other than square] cross-section, rolled on four faces, or of circular cross-section (other than of high-speed steel, silico-manganese steel, tool steel, articles of subheading 7228.30.49 and excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72284010": "Bars and rods of tool steel, only forged (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72284090": "Bars and rods of alloy steel, other than stainless steel, only forged (excl. of high-speed steel, silico-manganese steel, tool steel, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72285020": "Bars and rods of tool steel, only cold-formed or cold-finished (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72285040": "Bars and rods of steel containing 0,9% to 1,15% of carbon, 0,5% to 2% of chromium and, if present <= 0,5% of molybdenum, only cold-formed or cold-finished (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72285061": "Bars and rods of alloy steel, other than stainless steel, not further worked than cold-formed or cold-finished, of circular cross-section, of a diameter of >= 80 mm (excl. of high-speed steel, silico-manganese steel, tool steel, articles of subheading 7228.50.40, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72285069": "Bars and rods of alloy steel, other than stainless steel, not further worked than cold-formed or cold-finished, of circular cross-section, of a diameter of < 80 mm (excl. of high-speed steel, silico-manganese steel, tool steel, articles of subheading 7228.50.40, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72285080": "Bars and rods of alloy steel, other than stainless steel, not further worked than cold-formed or cold-finished (excl. of circular cross-section and products of high-speed steel, silico-manganese steel, tool steel, articles of subheading 7228.50.40, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72286020": "Bars and rods of tool steel, cold-formed or cold-finished and further worked or hot-formed and further worked (excl. semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72286080": "Bars and rods of alloy steel, other than stainless steel, cold-formed or cold-finished and further worked or hot-formed and further worked (excl. bars and rods of high-speed steel, silico-manganese steel or tool steel, semi-finished products, flat-rolled products and hot-rolled bars and rods in irregularly wound coils)",
    "72287010": "Angles, shapes and sections of alloy steel other than stainless, not further worked than hot-rolled, hot-drawn or extruded",
    "72287090": "Angles, shapes and sections of alloy steel other than stainless, n.e.s. (excl. products not further worked than hot-rolled, hot-drawn or extruded)",
    "72288000": "Hollow drill bars and rods, of alloy or non-alloy steel",
    "72292000": "Wire of silico-manganese steel, in coils (excl. bars and rods)",
    "72299020": "Wire of high-speed steel, in coils (excl. bars and rods)",
    "72299050": "Wire of steel containing by weight 0,9% to 1,1% of carbon, 0,5% to 2% of chromium and, if present, <= 0,5% of molybdenum, in coils (excl. rolled bars and rods)",
    "72299090": "Wire of alloy steel other than stainless, in coils (excl. rolled bars and rods, wire of high-speed steel or silico-manganese steel and articles of subheading 7229.90.50)",
    "73011000": "Sheet piling of iron or steel, whether or not drilled, punched or made from assembled elements",
    "73012000": "Angles, shapes and sections, of iron or steel, welded",
    "73021010": "Current-conducting rails of iron or steel, with parts of non-ferrous metal, for railway or tramway track (excl. check-rails)",
    "73021022": "Vignole rails of iron or steel, for railway or tramway track, new, of a weight of >= 36 kg/m",
    "73021028": "Vignole rails of iron or steel, for railway or tramway track, new, of a weight of < 36 kg/m",
    "73021040": "Grooved rails of iron or steel, for railway or tramway track, new",
    "73021050": "Rails of iron or steel, for railway or tramway track, new (excl. vignole rails, grooved rails, and current-conducting rails with parts of non-ferrous metal)",
    "73021090": "Rails of iron or steel, for railway or tramway track, used (excl. current-conducting rails with parts of non-ferrous metal)",
    "73023000": "Switch blades, crossing frogs, point rods and other crossing pieces, for railway or tramway track, of iron or steel",
    "73024000": "Fish-plates and sole plates of iron or steel, for railways or tramways",
    "73029000": "Sleepers \"cross-ties\", check-rails, rack rails, chairs, chair wedges, rail clips, bedplates and ties and other specialised material for the jointing or fixing of railway or tramway track, of iron or steel (excl. rails, switch blades, crossing frogs, point rods and other crossing pieces, and fish-plates and sole plates)",
    "73030010": "Tubes and pipes of a kind used in pressure systems, of cast iron",
    "73030090": "Tubes, pipes and hollow profiles, of cast iron (excl. products of a kind used in pressure systems)",
    "73041100": "Line pipe of a kind used for oil or gas pipelines, seamless, of stainless steel",
    "73041910": "Line pipe of a kind used for oil or gas pipelines, seamless, of iron or steel, of an external diameter of <= 168,3 mm (excl. products of stainless steel or of cast iron)",
    "73041930": "Line pipe of a kind used for oil or gas pipelines, seamless, of iron or steel, of an external diameter of > 168,3 mm but <= 406,4 mm (excl. products of stainless steel or of cast iron)",
    "73041990": "Line pipe of a kind used for oil or gas pipelines, seamless, of iron or steel, of an external diameter of > 406,4 mm (excl. products of stainless steel or of cast iron)",
    "73042200": "Drill pipe, seamless, of stainless steel, of a kind used in drilling for oil or gas",
    "73042300": "Drill pipe, seamless, of a kind used in drilling for oil or gas, of iron or steel (excl. products of stainless steel or of cast iron)",
    "73042400": "Casing and tubing, seamless, of a kind used for drilling for oil or gas, of stainless steel",
    "73042910": "Casing and tubing of a kind used for drilling for oil or gas, seamless, of iron or steel, of an external diameter <= 168,3 mm (excl. products of cast iron)",
    "73042930": "Casing and tubing of a kind used for drilling for oil or gas, seamless, of iron or steel, of an external diameter > 168,3 mm, but <= 406,4 mm (excl. products of cast iron)",
    "73042990": "Casing and tubing of a kind used for drilling for oil or gas, seamless, of iron or steel, of an external diameter > 406,4 mm (excl. products of cast iron)",
    "73043120": "Precision tubes, seamless, of circular cross-section, of iron or non-alloy steel, cold-drawn or cold-rolled \"cold-reduced\" (excl. line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used for drilling for oil or gas)",
    "73043180": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of iron or non-alloy steel, cold-drawn or cold-rolled \"cold-reduced\" (excl. cast iron products, line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil or gas and precision tubes)",
    "73043950": "Threaded or threadable tubes \"gas pipe\", seamless, of iron or non-alloy steel (excl. of cast iron)",
    "73043982": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of iron or non-alloy steel, of an external diameter of <= 168,3 mm (excl. cold-drawn or cold-rolled, of cast iron, line pipe of a kind used for oil or gas pipelines, casing, tubing and drill pipe of a kind used in drilling for oil or gas and tubes, and gas pipes of subheading 7304 39 50)",
    "73043983": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of iron or non-alloy steel, of an external diameter of > 168,3 mm but <= 406,4 mm (excl. cold-drawn or cold-rolled, of cast iron, line pipe of a kind used for oil or gas pipelines, casing, tubing and drill pipe of a kind used in drilling for oil or gas and tubes, and gas pipes of subheading 7304 39 50)",
    "73043988": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of iron or non-alloy steel, of an external diameter of > 406,4 mm (excl. cold-drawn or cold-rolled, of cast iron, line pipe of a kind used for oil or gas pipelines, casing, tubing and drill pipe of a kind used in drilling for oil or gas and tubes, and gas pipes of subheading 7304 39 50)",
    "73044100": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of stainless steel, cold-drawn or cold-rolled \"cold-reduced\" (excl. line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil or gas)",
    "73044983": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of stainless steel, of an external diameter of <= 168,3 mm (excl. cold-drawn or cold-rolled, line pipe of a kind used for oil or gas pipelines, and casing and tubing of a kind used for drilling for oil or gas and tubes)",
    "73044985": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of stainless steel, of an external diameter of > 168,3 mm but <= 406,4 mm (excl. cold-drawn or cold-rolled, line pipe of a kind used for oil or gas pipelines, and casing and tubing of a kind used for drilling for oil or gas and tubes)",
    "73044989": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of stainless steel, of an external diameter of > 406,4 mm (excl. cold-drawn or cold-rolled, line pipe of a kind used for oil or gas pipelines, and casing and tubing of a kind used for drilling for oil or gas and tubes)",
    "73045110": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of alloy steel other than stainless, cold-drawn or cold-rolled \"cold-reduced\", straight and of uniform wall-thickness, containing by weight >= 0,9% but <= 1,15% carbon and >= 0,5% but <= 2% chromium, whether or not containing by weight <= 0,5% molybdenum (excl. tubes, pipes and hollow profiles of subheadings 7304 19 to 7304 29)",
    "73045181": "Precision tubes, seamless, of circular cross-section, of alloy steel other than stainless, cold-drawn or cold-rolled \"cold-reduced\" (excl. line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil and tubes, and pipes and hollow profiles, straight and of uniform wall-thickness, containing by weight >= 0,9% but <= 1,15% carbon and >= 0,5% but <= 2% chrome, whether or not containing by weight <= 0,5% molybdenum)",
    "73045189": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of alloy steel other than stainless, not cold-drawn or cold-rolled \"cold-reduced\" (excl. line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil, precision tubes, and , pipes and hollow profiles, straight and of uniform wall-thickness, containing by weight >= 0,9% but <= 1,15% carbon and >= 0,5% but <= 2% chrome, whether or not containing by weight <= 0,5% molybdenum)",
    "73045930": "Tubes, pipes and hollow profiles of alloy steel (excl. stainless), seamless, of circular cross-section (not cold-drawn or cold-rolled), straight and of uniform wall-thickness, containing by weight >= 0,9% but <= 1,15% carbon and >= 0,5% but <= 2% chromium, whether or not containing by weight <= 0,5% molybdenum (excl. tubes, pipes and hollow profiles of subheadings 7304 19 to 7304 29)",
    "73045982": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of alloy steel other than stainless, of an external diameter of <= 168,3 mm (excl. cold-drawn or cold-rolled, line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil or gas, and products of subheading 7304 59 30)",
    "73045983": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of alloy steel other than stainless, of an external diameter of > 168,3 mm but <= 406,4 mm (excl. cold-drawn or cold-rolled, line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil or gas, and products of subheading 7304 59 30)",
    "73045989": "Tubes, pipes and hollow profiles, seamless, of circular cross-section, of alloy steel other than stainless, of an external diameter of > 406,4 mm (excl. cold-drawn or cold-rolled, line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used for drilling for oil or gas, and products of subheading 7304 59 30)",
    "73049000": "Tubes, pipes and hollow profiles, seamless, of non-circular cross-section, of iron or steel (excl. products of cast iron)",
    "73051100": "Line pipe of a kind used for oil or gas pipelines, having circular cross-sections and an external diameter of > 406,4 mm, of iron or steel, longitudinally submerged arc welded",
    "73051200": "Line pipe of a kind used for oil or gas pipelines, having circular cross-sections and an external diameter of > 406,4 mm, of iron or steel, longitudinally arc welded (excl. products longitudinally submerged arc welded)",
    "73051900": "Line pipe of a kind used for oil or gas pipelines, having circular cross-sections and an external diameter of > 406,4 mm, of flat-rolled products of iron or steel (excl. products longitudinally arc welded)",
    "73052000": "Casing of a kind used in drilling for oil or gas, having circular cross-sections and an external diameter of > 406,4 mm, of flat-rolled products of iron or steel",
    "73053100": "Tubes and pipes having circular cross-sections and an external diameter of > 406,4 mm, of iron or steel, longitudinally welded (excl. products of a kind used for oil or gas pipelines or of a kind used in drilling for oil or gas)",
    "73053900": "Tubes and pipes having circular cross-sections and an external diameter of > 406,4 mm, of iron or steel, welded (excl. products longitudinally welded or of a kind used for oil or gas pipelines or of a kind used in drilling for oil or gas)",
    "73059000": "Tubes and pipes having circular cross-sections and an external diameter of > 406,4 mm, of flat-rolled products of iron or steel, welded (excl. welded products or products of a kind used for oil or gas pipelines or of a kind used in drilling for oil or gas)",
    "73061100": "Line pipe of a kind used for oil or gas pipelines, welded, of flat-rolled products of stainless steel, of an external diameter of <= 406,4 mm",
    "73061900": "Line pipe of a kind used for oil or gas pipelines, welded, of flat-rolled products of iron or steel, of an external diameter of <= 406,4 mm (excl. products of stainless steel or of cast iron)",
    "73062100": "Casing and tubing of a kind used in drilling for oil or gas, welded, of flat-rolled products of stainless steel, of an external diameter of <= 406,4 mm",
    "73062900": "Casing and tubing of a kind used in drilling for oil or gas, welded, of flat-rolled products of iron or steel, of an external diameter of <= 406,4 mm (excl. products of stainless steel or of cast iron)",
    "73063012": "Precision tubes, welded, of circular cross-section, of iron or non-alloy steel, cold-drawn or cold-rolled \"cold-reduced\"",
    "73063018": "Precision tubes, welded, of circular cross-section, of iron or non-alloy steel (excl. cold-drawn or cold-rolled)",
    "73063041": "Threaded or threadable tubes \"gas pipe\", welded, of circular cross-section, of iron or non-alloy steel, plated or coated with zinc",
    "73063049": "Threaded or threadable tubes \"gas pipe\", welded, of circular cross-section, of iron or non-alloy steel (excl. products plated or coated with zinc)",
    "73063072": "Other tubes, pipes and hollow profiles, welded, of circular cross-section, of iron or non-alloy steel, of an external diameter of <= 168,3 mm, plated or coated with zinc (excl. line pipe of a kind used for oil or gas pipelines or casing and tubingof a kind used in drilling for oil or gas)",
    "73063077": "Other tubes, pipes and hollow profiles, welded, of circular cross-section, of iron or non-alloy steel of an external diameter of <= 168,3 mm (excl. plated or coated with zinc and line pipe of a kind used for oil or gas pipelines, casing and tubing of a kind used in drilling for oil or gas, precision tubes and threaded or threadable tubes \"gas pipe\")",
    "73063080": "Tubes, pipes and hollow profiles, welded, having a circular cross-section, of iron or steel, of an external diameter of > 168,3 mm but <= 406,4 mm (excl. line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used in drilling for oil or gas, or precision steel tubes, electrical conduit tubes or threaded or threadable tubes \"gas pipe\")",
    "73064020": "Tubes, pipes and hollow profiles, welded, of circular cross-section, of stainless steel, cold-drawn or cold-rolled \"cold-reduced\" (excl. products having internal and external circular cross-sections and an external diameter of > 406,4 mm, and line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used in drilling for oil or gas)",
    "73064080": "Tubes, pipes and hollow profiles, welded, of circular cross-section, of stainless steel (excl. products cold-drawn or cold-rolled \"cold-reduced\", tubes and pipes having internal and external circular cross-sections and an external diameter of > 406,4 mm, and line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used in drilling for oil or gas)",
    "73065021": "Precision steel tubes, welded, of circular cross-section, of alloy steel other than stainless, cold-drawn or cold-rolled \"cold-reduced\"",
    "73065029": "Precision steel tubes, welded, of circular cross-section, of alloy steel other than stainless (excl. cold-drawn or cold-rolled)",
    "73065080": "Tubes, pipes and hollow profiles, welded, of circular cross-section, of alloy steel other than stainless (excl. tubes and pipes having internal and external circular cross-sections and an external diameter of > 406,4 mm, and line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used in drilling for oil or gas, and precision steel tubes)",
    "73066110": "Tubes and pipes and hollow profiles, welded, of square or rectangular cross-section, of stainless steel",
    "73066192": "Tubes and pipes and hollow profiles, welded, of square or rectangular cross-section, of iron or steel other than stainless steel, with a wall thickness of <= 2 mm",
    "73066199": "Tubes and pipes and hollow profiles, welded, of square or rectangular cross-section, of iron or steel other than stainless steel, with a wall thickness of > 2 mm",
    "73066910": "Tubes, pipes and hollow profiles, welded, of non-circular cross-section, of stainless steel (excl. tubes and pipes having internal and external circular cross-sections and an external diameter of > 406,4 mm, line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used in drilling for oil or gas, and tubes and pipes and hollow profiles of square or rectangular cross-section)",
    "73066990": "Tubes, pipes and hollow profiles, welded, of non-circular cross-section, of iron or steel other than stainless steel (excl. tubes and pipes having internal and external circular cross-sections and an external diameter of > 406,4 mm, line pipe of a kind used for oil or gas pipelines or casing and tubing of a kind used in drilling for oil or gas, and tubes and pipes and hollow profiles of square or rectangular cross-section)",
    "73069000": "Tubes, pipes and hollow profiles \"e.g., open seam, riveted or similarly closed\", of iron or steel (excl. of cast iron, seamless or welded tubes and pipes and tubes and pipes having internal and external circular cross-sections and an external diameter of > 406,4 mm)",
    "73071110": "Tube or pipe fittings of non-malleable cast iron, of a kind used in pressure systems",
    "73071190": "Tube or pipe fittings of non-malleable cast iron (excl. products of a kind used in pressure systems)",
    "73071910": "Tube or pipe fittings of cast iron (excl. of non-malleable)",
    "73071990": "Cast tube or pipe fittings of steel",
    "73072100": "Flanges of stainless steel (excl. cast products)",
    "73072210": "Sleeves, of stainless steel, threaded (excl. cast products)",
    "73072290": "Elbows and bends, of stainless steel, threaded (excl. cast products)",
    "73072310": "Butt welding elbows and bends of stainless steel (excl. cast products)",
    "73072390": "Butt welding tube or pipe fittings of stainless steel (excl. cast products and elbows and bends)",
    "73072910": "Threaded tube or pipe fittings of stainless steel (excl. cast products, flanges, elbows, bends and sleeves)",
    "73072980": "Tube or pipe fittings of stainless steel (excl. cast, threaded, butt welding fittings and flanges)",
    "73079100": "Flanges of iron or steel (excl. cast or stainless products)",
    "73079210": "Sleeves of iron or steel, threaded (excl. cast or of stainless steel)",
    "73079290": "Elbows and bends, of iron or steel, threaded (excl. cast or of stainless steel)",
    "73079311": "Butt welding elbows and bends, of iron or steel, with greatest external diameter <= 609,6 mm (excl. cast iron or stainless steel products)",
    "73079319": "Butt welding fittings of iron or steel, with greatest external diameter <= 609,6 mm (excl. cast iron or stainless steel products, elbows, bends and flanges)",
    "73079391": "Butt welding elbows and bends, of iron or steel, with greatest external diameter > 609,6 mm (excl. cast iron or stainless steel products)",
    "73079399": "Butt welding fittings of iron or steel, with greatest external diameter > 609,6 mm (excl. cast iron or stainless steel products, elbows, bends and flanges)",
    "73079910": "Threaded tube or pipe fittings, of iron or steel (excl. cast iron or stainless steel products, flanges, elbows, bends and sleeves)",
    "73079980": "Tube or pipe fittings, of iron or steel (excl. of cast iron or stainless steel, threaded, butt welding fittings, and flanges)",
    "73081000": "Bridges and bridge-sections, of iron or steel",
    "73082000": "Towers and lattice masts, of iron or steel",
    "73083000": "Doors, windows and their frames and thresholds for doors, of iron or steel",
    "73084000": "Equipment for scaffolding, shuttering, propping or pit-propping (excl. composite sheetpiling products and formwork panels for poured-in-place concrete, which have the characteristics of moulds)",
    "73089051": "Panels comprising two walls of profiled \"ribbed\" sheet, of iron or steel, with an insulating core",
    "73089059": "Structures and parts of structures, of iron or steel, solely or principally of sheet, n.e.s. (excl. doors and windows and their frames, and panels comprising two walls of profiled \"ribbed\" sheet, of iron or steel, with an insulating core)",
    "73089098": "Structures and parts of structures of iron or steel, n.e.s. (excl. bridges and bridge-sections; towers; lattice masts; doors, windows and their frames and thresholds; equipment for scaffolding, shuttering, propping or pit-propping, and products made principally of sheet)",
    "73090010": "Reservoirs, tanks, vats and similar containers, of iron or steel, for gases other than compressed or liquefied gas, of a capacity of > 300 l (excl. containers fitted with mechanical or thermal equipment and containers specifically constructed or equipped for one or more types of transport)",
    "73090030": "Reservoirs, tanks, vats and similar containers, of iron or steel, for liquids, lined or heat-insulated and of a capacity of > 300 l (excl. containers fitted with mechanical or thermal equipment and containers specifically constructed or equipped for one or more types of transport)",
    "73090051": "Reservoirs, tanks, vats and similar containers, of iron or steel, for liquids, of a capacity of > 100.000 l (excl. containers lined or heat-insulated or fitted with mechanical or thermal equipment and containers specifically constructed or equipped for one or more types of transport)",
    "73090059": "Reservoirs, tanks, vats and similar containers, of iron or steel, for liquids, of a capacity of <= 100.000 l but > 300 l (excl. containers lined or heat-insulated or fitted with mechanical or thermal equipment and containers specifically constructed or equipped for one or more types of transport)",
    "73090090": "Reservoirs, tanks, vats and similar containers, of iron or steel, for solids, of a capacity of > 300 l (excl. containers lined or heat-insulated or fitted with mechanical or thermal equipment and containers specifically constructed or equipped for one or more types of transport)",
    "73101000": "Tanks, casks, drums, cans, boxes and similar containers, of iron or steel, for any material, of a capacity of >= 50 l but <= 300 l, n.e.s. (excl. containers for compressed or liquefied gas, or containers fitted with mechanical or thermal equipment)",
    "73102111": "Cans of iron or steel, of a capacity of < 50 l, which are to be closed by soldering or crimping, of a kind used for preserving food",
    "73102119": "Cans of iron or steel, of a capacity of < 50 l, which are to be closed by soldering or crimping, of a kind used for preserving drink",
    "73102191": "Cans of iron or steel, of a capacity of < 50 l, which are to be closed by soldering or crimping, of a wall thickness of < 0,5 mm (excl. cans for compressed or liquefied gas, and cans of a kind used for preserving food and drink)",
    "73102199": "Cans of iron or steel, of a capacity of < 50 l, which are to be closed by soldering or crimping, of a wall thickness of >= 0,5 mm (excl. cans for compressed or liquefied gas, and cans of a kind used for preserving food and drink)",
    "73102910": "Tanks, casks, drums, cans, boxes and similar containers, of iron or steel, for any material, of a capacity of < 50 l and of a wall thickness of < 0,5 mm, n.e.s. (excl. containers for compressed or liquefied gas, or containers fitted with mechanical or thermal equipment, and cans which are to be closed by soldering or crimping)",
    "73102990": "Tanks, casks, drums, cans, boxes and similar containers, of iron or steel, for any material, of a capacity of < 50 l and of a wall thickness of >= 0,5 mm, n.e.s. (excl. containers for compressed or liquefied gas, or containers fitted with mechanical or thermal equipment, and cans which are to be closed by soldering or crimping)",
    "73110011": "Containers of iron or steel, seamless, for compressed or liquefied gas, for a pressure >= 165 bar, of a capacity < 20 l (excl. containers specifically constructed or equipped for one or more types of transport)",
    "73110013": "Containers of iron or steel, seamless, for compressed or liquefied gas, for a pressure >= 165 bar, of a capacity >= 20 l to <= 50 l (excl. containers specifically constructed or equipped for one or more types of transport)",
    "73110019": "Containers of iron or steel, seamless, for compressed or liquefied gas, for a pressure >= 165 bar, of a capacity > 50 l (excl. containers specifically constructed or equipped for one or more types of transport)",
    "73110030": "Containers of iron or steel, seamless, for compressed or liquefied gas, for a pressure < 165 bar (excl. containers specifically constructed or equipped for one or more types of transport)",
    "73110091": "Containers of iron or steel, seamless, for compressed or liquefied gas, of a capacity of < 1.000 l (excl. seamless containers and containers specifically constructed or equipped for one or more types of transport)",
    "73110099": "Containers of iron or steel, seamless, for compressed or liquefied gas, of a capacity of >= 1.000 l (excl. seamless containers and containers specifically constructed or equipped for one or more types of transport)",
    "73181100": "Coach screws of iron or steel",
    "73181210": "Wood screws of stainless steel (excl. coach screws)",
    "73181290": "Wood screws of iron or steel other than stainless (excl. coach screws)",
    "73181300": "Screw hooks and screw rings, of iron or steel",
    "73181410": "Self-tapping screws, of stainless steel (excl. wood screws)",
    "73181491": "Spaced-thread screws of iron or steel other than stainless",
    "73181499": "Self-tapping screws of iron or steel other than stainless (excl. spaced-thread screws and wood screws)",
    "73181520": "Screws and bolts, of iron or steel \"whether or not with their nuts and washers\", for fixing railway track construction material (excl. coach screws)",
    "73181535": "Screws and bolts, of stainless steel \"whether or not with their nuts and washers\", without heads (excl. screws and bolts for fixing railway track construction material)",
    "73181542": "Screws and bolts, of iron or steel other than stainless \"whether or not with their nuts and washers\", without heads, with a tensile strength of < 800 MPa (excl. screws and bolts for fixing railway track construction material)",
    "73181548": "Screws and bolts, of iron or steel other than stainless \"whether or not with their nuts and washers\", without heads, with a tensile strength of >= 800 MPa (excl. screws and bolts for fixing railway track construction material)",
    "73181552": "Screws and bolts, of stainless steel \"whether or not with their nuts and washers\", with slotted or cross-recessed heads (excl. wood screws and self-tapping screws)",
    "73181558": "Screws and bolts, of iron or steel other than stainless \"whether or not with their nuts and washers\", with slotted or cross-recessed heads (excl. wood screws and self-tapping screws)",
    "73181562": "Hexagonal-socket head screws and bolts, of stainless steel \"whether or not with their nuts and washers\" (excl. wood screws, self-tapping screws and screws and bolts for fixing railway track construction material)",
    "73181568": "Hexagonal-socket head screws and bolts, of iron or steel other than stainless \"whether or not with their nuts and washers\" (excl. wood screws, self-tapping screws and screws and bolts for fixing railway track construction material)",
    "73181575": "Hexagon screws and bolts, of stainless steel \"whether or not with their nuts and washers\" (excl. with socket head, wood screws, self-tapping screws and screws and bolts for fixing railway track construction material)",
    "73181582": "Hexagon screws and bolts, of iron or steel other than stainless \"whether or not with their nuts and washers\", with a tensile strength of < 800 MPa (excl. with socket head, wood screws, self-tapping screws and screws and bolts for fixing railway track construction material)",
    "73181588": "Hexagon screws and bolts, of iron or steel other than stainless \"whether or not with their nuts and washers\", with a tensile strength of => 800 MPa (excl. with socket head, wood screws, self-tapping screws and screws and bolts for fixing railway track construction material)",
    "73181595": "Screws and bolts, of iron or steel \"whether or not with their nuts and washers\", with heads (excl. with slotted, cross-recessed or hexagonal head; wood screws, self-tapping screws and screws and bolts for fixing railway track construction material, screw hooks and screw rings)",
    "73181631": "Blind rivet nuts of stainless steel",
    "73181639": "Nuts of stainless steel (excl. blind rivet nuts)",
    "73181640": "Blind rivet nuts of iron or steel other than stainless",
    "73181660": "Self-locking nuts of iron or steel other than stainless",
    "73181692": "Nuts of iron or steel other than stainless, with an inside diameter <= 12 mm (excl. blind rivet nuts and self-locking nuts)",
    "73181699": "Nuts of iron or steel other than stainless, with an inside diameter > 12 mm (excl. blind rivet nuts and self-locking nuts)",
    "73181900": "Threaded articles, of iron or steel, n.e.s.",
    "73182100": "Spring washers and other lock washers, of iron or steel",
    "73182200": "Washers of iron or steel (excl. spring washers and other lock washers)",
    "73182300": "Rivets of iron or steel (excl. tubular and bifurcated rivets for particular uses)",
    "73182400": "Cotters and cotter pins, of iron or steel",
    "73182900": "Non-threaded articles, of iron or steel",
    "73261100": "Grinding balls and similar articles for mills, of iron or steel, forged or stamped, but not further worked",
    "73261910": "Articles of iron or steel, open-die forged, but not further worked, n.e.s. (excl. grinding balls and similar articles for mills)",
    "73261990": "Articles of iron or steel, closed-die forged or stamped, but not further worked, n.e.s. (excl. grinding balls and similar articles for mills)",
    "73262000": "Articles of iron or steel wire, n.e.s.",
    "73269030": "Ladders and steps, of iron or steel",
    "73269040": "Pallets and similar platforms for handling goods, of iron or steel",
    "73269050": "Reels for cables, piping and the like, of iron or steel",
    "73269060": "Ventilators, non-mechanical, guttering, hooks and like articles used in the building industry, n.e.s., of iron or steel",
    "73269092": "Articles of iron or steel, open-die forged, n.e.s.",
    "73269094": "Articles of iron or steel, closed-die forged, n.e.s.",
    "73269096": "Sintered articles of iron or steel, n.e.s.",
    "73269098": "Articles of iron or steel, n.e.s.",
};
